# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('displayName', models.CharField(max_length=128)),
                ('east0', models.FloatField()),
                ('north0', models.FloatField()),
                ('zone', models.CharField(max_length=8)),
                ('zoneNumber', models.IntegerField()),
                ('south', models.BooleanField()),
                ('axes', models.CharField(default=b'ENU', max_length=8)),
                ('north', models.CharField(max_length=8)),
                ('timezone', models.CharField(max_length=64)),
            ],
        ),
    ]
